### ISSUE TITLE
Enhance Katana Logging to Mirror Starknet Devnet Features

### ISSUE THREAD

**Issue by neotheprogramist** [neotheprogramist/dojo#1]
## Description
We aim to enhance the `katana` tool ([Katana Overview](https://book.dojoengine.org/toolchain/katana/overview.html)) to have logging capabilities similar to `starknet devnet` ([Starknet Devnet Repository](https://github.com/0xSpaceShard/starknet-devnet-rs)). This improvement is intended to provide better insights and debugging capabilities for developers using `katana`.

### Predeployed FeeToken Logs
- Log the address and class hash of the predeployed FeeToken.

### Predeployed UDC Logs
- Log the address and class hash of the predeployed UDC (Universal Deployer Contract).

### Predeployed Account Contract Logs
- Log the class hash of the predeployed Account contract.

### RPC Call Logs
- Include logs detailing specific RPC (Remote Procedure Call) calls.

## Purpose
This feature will assist developers in monitoring and debugging their smart contracts and transactions on the `katana` development network. Detailed logs, especially for predeployed contracts and RPC calls, are vital for efficient development workflows.

## Task
- Implement the above-mentioned logging features in the `katana` tool.
- Ensure that the logs are readable and accessible during runtime.

**Comment by matzayonc** [comment]
RPC call logs are already more specific on Katana than Devnet
![Image](https://github.com/neotheprogramist/dojo/assets/60236390/a19919ac-374c-4439-abf2-55f7330f01b4)
